services:

  app: &app
    build:
      dockerfile: dev.dockerfile
    depends_on:
      - db
    env_file:
      - .env
    platform: linux/amd64
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_home:/usr/local/bundle

  test:
    <<: *app
    command: bundle exec rails test
    environment:
      RAILS_ENV: test

  db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
    volumes:
      - db_data_dir:/var/lib/postgresql

volumes:

  db_data_dir:
  bundle_home:
